spring:
  profiles:
    active: ${ACTIVE_PROFILE:local}
  threads:
    virtual:
      enabled: ${VIRTUAL_THREADS_ENABLED:true}
  application:
    name: pinokio
  main:
    banner-mode: off
server:
  port: ${PORT:9999}
application:
  algorithm: ${HASHING_ALGORITHM:MURMUR32}
  max-hash-retries: ${MAX_HASH_ITERATIONS:3}
  dynamodb:
    region: ${AWS_REGION:us-east-1}
    table: ${DYNAMODB_TABLE:pinokio}
    access-key-id: ${AWS_ACCESS_KEY_ID:test} # Default value is used by LocalStack
    secret-access-key: ${AWS_SECRET_ACCESS_KEY:test} # Default value is used by LocalStack
    endpoint-url: ${DYNAMODB_ENDPOINT:http://localhost:4566} # Used by LocalStack only
  base-url: ${BASE_URL:http://localhost:9999}
  url-expiration-in-days: ${URL_EXPIRATION_IN_DAYS:90}